version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ver_1 .
